config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "diarys#index"
  resources :users, only: [:edit, :update]
  resources :charts, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assessment.rb
class Assessment < ApplicationRecord
end

app/models/chart.rb
class Chart < ApplicationRecord
  has_many :chart_users
  has_many :users, through: :chart_users

  validates :name, presence: true

end

app/models/chart_user.rb
class ChartUser < ApplicationRecord
  belongs_to :chart
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX

  with_options presence: true, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/ } do
    validates :nickname
    validates :firstname
    validates :lastname
  end
  with_options presence: true, format: { with: /\A[ァ-ヶ]+\z/ } do
    validates :firstname_kata
    validates :lastname_kata
  end
  validates :birthday, presence: true
  validates :profile, presence: true

  has_many :chart_users
  has_many :charts, through: :chart_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: [:nickname, :profile, :lastname, :firstname, :lastname_kata, :firstname_kata,
                                             :birthday])
  end
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  def index
  end
  
  def new
    @chart = Chart.new
  end

  def create
    @chart = Chart.new(chart_params.slice(:name))
    ApplicationRecord.transaction do
      @chart.save!
      @chart.users = User.where(id: chart_params[:user_ids])
      @chart.save!
    end
    redirect_to root_path
  rescue
    render :new
  end

  private
  def chart_params
    params.require(:chart).permit(:name, user_ids: [])
  end
end

app/controllers/diarys_controller.rb
class DiarysController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    current_user.update(user_params)
    if redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/diarys_helper.rb
module DiarysHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/charts/index.html.erb
<div class="chart-top">
  <h1>カルテ</h1>
</div>

<div class="chart-menu">
  <h2>初回・2回目以降の身体評価はここから</h3>
  <h2>日々のエクササイズ記録はここから</h2>
</div>

app/views/charts/new.html.erb
<div class='chat-room-form'>
  <h1>新しくカルテを作る</h1>
  <%=form_with model: @chart, local: true do |f|%>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :name, :カルテ名, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :name, class: 'chat__room_name chat-room-form__input', placeholder: 'カルテ名を入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <label class='chat-room-form__label' for='chat_room_チャットメンバー'>アドバイザーリスト</label>
      </div>
      <div class='chat-room-form__field--right'>
        <select name="chart[user_ids][]">
          <option value="">クリニック所属のアドバイザーを選択してください</option>
          <% User.where.not(id: current_user.id).each do |user| %>
            <option value=<%= user.id %>><%= user.nickname %><%= user.lastname %><%= user.firstname %></option>
          <% end %>
        </select>
        <input name="chart[user_ids][]" type="hidden" value=<%= current_user.id %>>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/diarys/index.html.erb
<!doctype html>
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Cover Template · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/cover/">



    <!-- Bootstrap core CSS -->
<link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="cover.css" rel="stylesheet">
  </head>
  <body class="d-flex h-100 text-center text-white bg-dark">
    
<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="mb-auto">
    <div>
      <h3 class="float-md-start mb-0">P h y s i c a l - P l a n</h3>
      <nav class="nav nav-masthead justify-content-center float-md-end">
        <a class="nav-link active" aria-current="page" href="#">Home</a>
        <% if user_signed_in? %>
          <%= link_to current_user.nickname, edit_user_path(current_user), class: "nav-link" %>
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %>
          <%= link_to "カルテ作成", new_chart_path, class: "nav-link" %>
          <% current_user.charts.each do |chart| %>
            <a href="/charts" class="nav-link"><%= chart.name %></a>
          <% end %>
        <% else %>
          <a class="nav-link" href="/users/sign_up">Signup</a>
          <a class="nav-link" href="/users/sign_in">Login</a>
        <% end %>
      </nav>
    </div>
  </header>

  <main class="px-3">
    <h1>あなただけの特別なプランを。</h1>
    <p class="lead">マイカルテを作り、フィジカルパフォーマンスのサマリーを作成。ライプラン達成に影響し得るフィジカル因子の抽出と予測に基づくエクササイズを行い、いつまでもやりたいことができる人生に。</p>
    <p class="lead">
      <a href="/users/sign_up" class="text-dark btn btn-lg btn-secondary fw-bold border-white bg-white">新規登録してはじめる</a>
    </p>
  </main>

  <footer class="mt-auto text-white-50">
    <p>Physical-Plan Inc. 2022</p>
  </footer>
</div>


    
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhysicalPlan</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<%# 下部広告部分 %>
<div class='ad-footer-contents'>
  <p class='ad-footer-explain'>
    だれでもかんたん、人生を変えるフリマアプリ
  </p>
  <h2 class='ad-footer-title'>
    今すぐ無料ダウンロード！
  </h2>
  <div class='store-btn'>
    <%= link_to image_tag("app-store.svg", class:"apple-btn"), "#" %>
    <%= link_to image_tag("google-play.png", class:"google-btn"), "#" %>
  </div>
</div>
<%# /下部広告部分 %>

<div class='footer'>
  <div class='footer-contents'>
    <div class='furima-details'>
      <h2 class='footer-content-head'>FURIMAについて</h2>
      <ul>
        <li><%= link_to '会社概要（運営会社)', "#", class: "footer-link" %></li>
        <li><%= link_to 'プライバシーポリシー', "#", class: "footer-link" %></li>
        <li><%= link_to 'FURIMA利用規約', "#", class: "footer-link" %></li>
        <li><%= link_to 'ポイントに関する特約', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>FURIMAを見る</h2>
      <ul>
        <li><%= link_to 'カテゴリー一覧', "#", class: "footer-link" %></li>
        <li><%= link_to 'ブランド一覧', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>FURIMAについて</h2>
      <ul>
        <li><%= link_to 'FURIMAガイド', "#", class: "footer-link" %></li>
        <li><%= link_to 'FURIMAロゴ利用ガイドライン', "#", class: "footer-link" %></li>
        <li><%= link_to 'お知らせ', "#", class: "footer-link" %></li>
      </ul>
    </div>
  </div>
  <%= link_to image_tag("furima-logo-white.png", class:"logo-white"), "#" %>
  <p>© FURIMA</p>
</div>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <%= link_to image_tag("furima-logo-color.png", class:"furima-icon"), "/" %>
    <form class="search-form" action="#">
      <input class='input-box' placeholder='キーワードから探す'>
      <button class="search-button">
        <%= image_tag "search.png", class:"search-icon" %>
      </button>
    </form>
  </div>
  <div class='nav'>
    <ul class='lists-left'>
      <li><%= link_to 'カテゴリー', "#", class: "category-list" %></li>
      <li><%= link_to 'ブランド', "#", class: "brand-list" %></li>
    </ul>
    <ul class='lists-right'>
      <%# deviseを導入できたら、ログインの有無で表示が変わるように分岐しましょう%>
      <%# <li><%= link_to current_user.nickname, "#", class: "user-nickname" </li> %>
      <%# <li><%= link_to 'ログアウト', "#", method: :delete, class: "logout" </li> %>
      <li><%= link_to 'ログイン', "#", class: "login" %></li>
      <li><%= link_to '新規登録', "#", class: "sign-up" %></li>
      <%# //deviseを導入できたら、ログインの有無で表示が変わるように分岐しましょう%>
    </ul>
  </div>
</header>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>
  <div class='second-fotter-text-wrap'>
    <p class='second-fotter-text'>プライバシーポリシー</p>
    <p class='second-fotter-text'>Physical Plan利用規約</p>
    <p class='second-fotter-text'>特定商取引に関する表記</p>
  </div>
  <%# <%= image_tag "furima-logo-color.png", class:"second-fotter-logo"%>
</footer>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%# <%= link_to image_tag("furima-logo-color.png", class:"second-logo"), "/" %>
</header>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>ユーザー登録情報の編集</h5>
      <%= link_to "トップページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :nickname, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>